#! /usr/bin/python

import os
import smtplib
import time


def send_email():
	with open('data.txt', 'wb') as ip_data:
		ip_data.write('To:adityamurray@yahoo.com\n')
		ip_data.write('From:ROBIN\n')
		ip_data.write('Subject:IP_DATA\n')
		ip_data.write('\n\n\n\n')
		os.system('echo "\n===========================================\n">>data.txt')
		os.system('echo >>data.txt')
		os.system('ifconfig>>data.txt')


	os.system('ssmtp adityamurray@yahoo.com<data.txt')

while(True):
	send_email()
	time.sleep(7200)
